log result

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -70,8 +70,15 @@ jobs:
         echo "Waiting for app to be ready..."
         counter=0
         max_retries=5
-        while ! curl -sSf http://localhost:3009/; do
-          echo "Waiting for app..."
+        while true; do
+          response=$(curl -sSf http://localhost:3009/ 2>&1)
+          if [ $? -eq 0 ]; then
+            echo "App is ready!"
+            break
+          else
+            echo "Waiting for app..."
+            echo "Error response: $response"
+          fi
           sleep 5
           counter=$((counter+1))
           if [ $counter -ge $max_retries ]; then
@@ -80,7 +87,7 @@ jobs:
             exit 1
           fi
         done
-        echo "App is ready!"
+    
 
     - name: Test
       run: |
